#
# Makefile for the dev channel
#

VERBOSE=-v
# VERBOSE=-v -v -i
CHANNEL=dev

include common.mk

## Public targets

TARGETS=\
	build-and-upload-packages \
	build-images \
	build-packages \
	burn-to-usb \
	code-is-current \
	compress-images \
	delete-all-vms-on-account \
	pacsane \
	purge \
	run-webapptests \
	run-webapptests-hl \
	run-webapptests-workout

build-packages : check-sign-packages-setup check-sign-dbs-setup
	GNUPGHOME=$(GNUPGHOME) macrobuild UBOS::Macrobuild::BuildTasks::BuildDev \
		--configdir "$(CONFIGDIR)" \
		--archUpstreamDir '$(ARCHUPSTREAMDIR)' \
		--arch "$(ARCH)" \
		--builddir "$(BUILDDIR)" \
		--repodir "$(REPODIR)" \
		--channel "$(CHANNEL)" \
		$(SIGNPACKAGESARG) \
		$(SIGNDBSARG) \
		$(VERBOSE)

build-and-upload-packages : check-sign-packages-setup check-sign-dbs-setup
	[ ! -z "$(ARCHUPSTREAMDIR)" ]
	GNUPGHOME=$(GNUPGHOME) macrobuild UBOS::Macrobuild::BuildTasks::BuildAndUploadDev \
		--configdir "$(CONFIGDIR)" \
		--archUpstreamDir '$(ARCHUPSTREAMDIR)' \
		--arch "$(ARCH)" \
		--builddir "$(BUILDDIR)" \
		--repodir "$(REPODIR)" \
		--channel "$(CHANNEL)" \
		--uploadDest "$(UPLOADDEST)" \
		--uploadSshKey "$(UPLOADSSHKEY)" \
		$(SIGNPACKAGESARG) \
		$(SIGNDBSARG) \
		$(VERBOSE)

