#
# Makefile for the dev channel
#

VERBOSE=-v
# VERBOSE=-v -v -i
CHANNEL=dev

-include local.mk
include common.mk

## Public targets

TARGETS=\
	build-images \
	build-packages \
	burn-to-usb \
	code-is-current \
	compress-images \
	delete-all-vms-on-account \
	pacsane \
	purge \
	upload \
	run-webapptests \
	run-webapptests-hl \
	run-webapptests-workout

ifdef LOCAL_SOURCES_DIR
build-packages : check-sign-packages-setup check-sign-dbs-setup
	GNUPGHOME=$(GNUPGHOME) macrobuild UBOS::Macrobuild::BuildTasks::BuildDev \
		--configdir "$(CONFIGDIR)" \
		--archUpstreamDir '$(ARCHUPSTREAMDIR)' \
		--arch "$(ARCH)" \
		--builddir "$(BUILDDIR)" \
		--repodir "$(REPODIR)" \
		--channel "$(CHANNEL)" \
		--localSourcesDir "$(LOCAL_SOURCES_DIR)" \
		$(SIGNPACKAGESARG) \
		$(SIGNDBSARG) \
		$(VERBOSE)
else
build-packages : check-sign-packages-setup check-sign-dbs-setup
	GNUPGHOME=$(GNUPGHOME) macrobuild UBOS::Macrobuild::BuildTasks::BuildDev \
		--configdir "$(CONFIGDIR)" \
		--archUpstreamDir '$(ARCHUPSTREAMDIR)' \
		--arch "$(ARCH)" \
		--builddir "$(BUILDDIR)" \
		--repodir "$(REPODIR)" \
		--channel "$(CHANNEL)" \
		$(SIGNPACKAGESARG) \
		$(SIGNDBSARG) \
		$(VERBOSE)
endif
